app/api/models.py
## -*- coding: utf-8 -*-

app/sites/rooms/models.py
## -*- coding: utf-8 -*-

app/user/models.py
## -*- coding: utf-8 -*-

from app import db
from flask_security import UserMixin, RoleMixin

roles_users = db.Table('roles_users',
        db.Column('user_id', db.Integer(), db.ForeignKey('user.id')),
        db.Column('role_id', db.Integer(), db.ForeignKey('role.id')))

class Role(db.Model, RoleMixin):
    id = db.Column(db.Integer(), primary_key=True)
    name = db.Column(db.String(80), unique=True)
    description = db.Column(db.String(255))

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(255), unique=True)
    password = db.Column(db.String(255))
    name = db.Column(db.String())
    active = db.Column(db.Boolean())
    confirmed_at = db.Column(db.DateTime())
    last_login_at = db.Column(db.DateTime())
    current_login_at = db.Column(db.DateTime())
    last_login_ip = db.Column(db.String())
    current_login_ip = db.Column(db.String())
    login_count = db.Column(db.Integer())

    roles = db.relationship('Role', secondary=roles_users,
                            backref=db.backref('users', lazy='dynamic'))

app/api/forms.py
## -*- coding: utf-8 -*-

app/map/forms.py
## -*- coding: utf-8 -*-

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectMultipleField, SelectField, IntegerField, DateField, BooleanField
from wtforms.validators import InputRequired
from app.services.services import select2MultipleWidget, select2Widget

class searchForm(FlaskForm):
    destCity = StringField('Destination City')
    currency = SelectField('Currency', choices=[('DKK','DKK')])
    available = BooleanField('Show only available rooms')
    checkin = DateField('Check In', format="%Y-%m-%d")
    checkout = DateField('Check Out', format="%Y-%m-%d")

app/sites/rooms/forms.py
## -*- coding: utf-8 -*-

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectMultipleField, SelectField, IntegerField, DateField, BooleanField
from wtforms.validators import InputRequired
from app.services.services import select2MultipleWidget, select2Widget

class searchRoomForm(FlaskForm):
    destCity = StringField('Destination City')
    currency = SelectField('Currency', choices=[('DKK','DKK')])
    available = BooleanField('Show only available rooms')
    checkin = DateField('Check In', format="%Y-%m-%d")
    checkout = DateField('Check Out', format="%Y-%m-%d")

app/sites/transport/forms.py
## -*- coding: utf-8 -*-

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, SelectMultipleField, SelectField, IntegerField, DateField, BooleanField
from wtforms.validators import InputRequired
from app.services.services import select2MultipleWidget, select2Widget

class searchTransportForm(FlaskForm):
    destCity = StringField('Destination City')
    currency = SelectField('Currency', choices=[('DKK','DKK')])
    available = BooleanField('Show only available cars')
    checkin = DateField('From date', format="%Y-%m-%d")
    checkout = DateField('To date', format="%Y-%m-%d")## -*- coding: utf-8 -*-

app/__init__.py
## -*- coding: utf-8 -*-

from flask import Flask, render_template
from flask_sqlalchemy import SQLAlchemy
from flask_mail import Mail
import flask_sijax
from flask_htmlmin import HTMLMIN
from flask_security import Security, SQLAlchemyUserDatastore

# Setup Flask and read config from ConfigClass defined above
app = Flask(__name__)
app.config.from_object('config.DevelopmentConfig')

# Flask-SQLAlchemy
db = SQLAlchemy(app)

# Flask-mail
mail = Mail(app)

# HTML min
HTMLMIN(app)

# Flask-sijax
flask_sijax.Sijax(app)

# Import models
from app.user.models import User, Role

# Flask-Security
user_datastore = SQLAlchemyUserDatastore(db, User, Role)
security = Security(app, user_datastore)

## import blueprints
from app.index.views import indexBP
from app.map.views import mapBP
from app.user.views import userBP
from app.sites.rooms.views import roomsBP
from app.sites.transport.views import transportBP

## Register blueprints
app.register_blueprint(indexBP, url_prefix='')
app.register_blueprint(mapBP, url_prefix='/map')
app.register_blueprint(userBP, url_prefix='/user')
app.register_blueprint(roomsBP, url_prefix='/rooms')
app.register_blueprint(transportBP, url_prefix='/transport')

# Error handlers


@app.route('/error404')
def error404():
    return render_template('errors/404.html')

app/api/__init__.py
## -*- coding: utf-8 -*-

app/api/views.py
## -*- coding: utf-8 -*-

from flask import render_template, Blueprint, request, url_for
from app.services.services import errorMessage, successMessage
from app import app

apiBP = Blueprint('apiBP', __name__)

app/index/__init__.py
## -*- coding: utf-8 -*-

app/index/views.py
## -*- coding: utf-8 -*-

from flask import render_template, Blueprint, request, url_for
from app.services.services import errorMessage, successMessage
from app import app

indexBP = Blueprint('indexBP', __name__)

# indexView
@indexBP.route('/')
def indexView():
    return render_template('index/index.html')

app/map/__init__.py
## -*- coding: utf-8 -*-

app/map/views.py
## -*- coding: utf-8 -*-

from flask import render_template, Blueprint, request, url_for, g, jsonify
from app.services.services import errorMessage, successMessage
from app import app
from sijax import SijaxHandler
import flask_sijax
from forms import searchForm

mapBP = Blueprint('mapBP', __name__)

@flask_sijax.route(mapBP, '/', methods=['GET'])
def mapView():

    if g.sijax.is_sijax_request:
        g.sijax.register_object(SijaxHandler)
        return g.sijax.process_request()

    form = searchForm(currency='DKK')

    return render_template('map/map.html', form=form)

app/services/__init__.py
## -*- coding: utf-8 -*-

from flask import flash
from app import mail
from flask_mail import Message
from wtforms import widgets

# Flash messages
def errorMessage(msg):
    return flash(unicode(msg), 'error')
def successMessage(msg):
    return flash(unicode(msg), 'success')

# SendMail
def sendMail(subject, sender, recipients, text_body, html_body):
    mesg = Message(subject, sender=sender, recipients=recipients)
    mesg.body = text_body
    mesg.html = html_body
    mail.send(mesg)

# WTForms widgets
# Select2 widget
class select2Widget(widgets.Select):
    def __call__(self, field, **kwargs):
        kwargs.setdefault('data-role', u'select2')

        allow_blank = getattr(field, 'allow_blank', False)
        if allow_blank and not self.multiple:
            kwargs['data-allow-blank'] = u'1'

        return super(select2Widget, self).__call__(field, **kwargs)

# Select2 multiple widget
class select2MultipleWidget(widgets.Select):
    def __call__(self, field, **kwargs):
        kwargs.setdefault('data-role', u'select2')
        allow_blank = getattr(field, 'allow_blank', False)
        if allow_blank and not self.multiple:
            kwargs['data-allow-blank'] = u'1'

        return super(select2MultipleWidget, self).__call__(field, multiple = True, **kwargs)

app/sites/__init__.py
## -*- coding: utf-8 -*-

app/sites/rooms/__init__.py
## -*- coding: utf-8 -*-

app/sites/rooms/views.py
## -*- coding: utf-8 -*-

from flask import render_template, Blueprint, request, url_for, g
from app.services.services import errorMessage, successMessage
from app import app
import flask_sijax
from sijax import SijaxHandler
from forms import searchRoomForm

roomsBP = Blueprint('roomsBP', __name__)

@flask_sijax.route(roomsBP, '/', methods=['GET'])
def roomMapSearchView():

    kwargs = {'title':'Search for rooms'}

    if g.sijax.is_sijax_request:
        g.sijax.register_object(SijaxHandler)
        return g.sijax.process_request()

    form = searchRoomForm(currency='DKK')

    return render_template('sites/rooms/rooms.html', form=form, **kwargs)

app/user/__init__.py
## -*- coding: utf-8 -*-

app/user/views.py
## -*- coding: utf-8 -*-

from flask import render_template, Blueprint, request, url_for
from app.services.services import errorMessage, successMessage
from app import app

userBP = Blueprint('userBP', __name__)

@userBP.route('/profile')
def userProfileView():

    return render_template('user/profile.html')

app/templates/base.html
{% block doc -%}
<!DOCTYPE html>
<html{% block html_attribs %}{% endblock html_attribs %}>
{%- block html %}
<head>
    {%- block head %}

    <title>{% block title %}Lendr{% endblock title %}</title>

    {%- block metas %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="utf-8">
    {%- endblock metas %}

    {%- block styles %}
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">

    {%- endblock styles %}
    {%- endblock head %}
</head>

<body{% block body_attribs %}{% endblock body_attribs %}>
    {% block body -%}

    {% block navbar %}
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{url_for('indexBP.indexView')}}">Lendr</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{{url_for('indexBP.indexView')}}">Home</a></li>

                    <li><a href="{{url_for('mapBP.mapView')}}">Map</a></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Sites <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{{url_for('roomsBP.roomMapSearchView')}}">rooms</a></li>
                            <li><a href="{{url_for('transportBP.transportMapSearchView')}}">transport</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Error pages <span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a href="{{url_for('error404')}}">Page not found</a></li>
                        </ul>
                    </li>

                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated %}
                    <li><a href="{{url_for('userBP.userProfileView')}}">Profile</a></li>
                    <li><a href="{{url_for('security.logout')}}">Logout</a></li>
                    {% else %}
                    <li><a href="{{url_for('security.login')}}">Login</a></li>
                    <li><a href="{{url_for('security.register')}}">Register Account</a></li>
                    {% endif %}
                </ul>
            </div><!--/.navbar-collapse -->
        </div>
    </nav>
    {%- endblock navbar %}
    {% block flashMessages -%}
    <div class="container-fluid flashMessageContainer">
            <div class="col">
                {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category[0] }} alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4>{{ category[0]|title }}</h4>
                        {{ message }}
                    </div>
                {% endfor %}
                {% endif %}
                {% endwith %}
            </div>
        </div>
    {% endblock flashMessages -%}

    <div class="container-fluid contentDiv">
        <div class="col">
            {% block content %}{% endblock %}
        </div>
    </div>

    {% block scripts %}
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <script type="text/javascript">
    // Ensures active class on active pages in navigation
    var url = window.location;
        // Will only work if string in href matches with location
        $('ul.nav a[href="'+ url +'"]').parent().addClass('active');

        // Will also work for relative and absolute hrefs
        $('ul.nav a').filter(function() {
            return this.href == url;
        }).parent().addClass('active');
    </script>

    <script type="text/javascript" src="/static/js/sijax/sijax.js"></script>
    <script type="text/javascript">{{ g.sijax.get_js()|safe }}</script>

    {%- endblock scripts %}
    {%- endblock body %}

</body>
{%- endblock html %}

</html>
{% endblock doc -%}

app/templates/security/_macros.html
{% macro render_field_with_errors(field) %}
  <p>
    {{ field.label }} {{ field(**kwargs)|safe }}
    {% if field.errors %}
      <ul>
      {% for error in field.errors %}
        <li>{{ error }}</li>
      {% endfor %}
      </ul>
    {% endif %}
  </p>
{% endmacro %}

{% macro render_field(field) %}
  <p>{{ field(**kwargs)|safe }}</p>
{% endmacro %}

app/templates/security/_menu.html
{% if security.registerable or security.recoverable or security.confirmable %}
<h2>Menu</h2>
<ul>
  <li><a href="{{ url_for_security('login') }}{% if 'next' in request.args %}?next={{ request.args.next|urlencode }}{% endif %}">Login</a></li>
  {% if security.registerable %}
  <li><a href="{{ url_for_security('register') }}{% if 'next' in request.args %}?next={{ request.args.next|urlencode }}{% endif %}">Register</a><br/></li>
  {% endif %}
  {% if security.recoverable %}
  <li><a href="{{ url_for_security('forgot_password') }}">Forgot password</a><br/></li>
  {% endif %}
  {% if security.confirmable %}
  <li><a href="{{ url_for_security('send_confirmation') }}">Confirm account</a></li>
  {% endif %}
</ul>
{% endif %}

app/templates/security/_messages.html
{%- with messages = get_flashed_messages(with_categories=true) -%}
  {% if messages %}
    <ul class="flashes">
    {% for category, message in messages %}
      <li class="{{ category }}">{{ message }}</li>
    {% endfor %}
    </ul>
  {% endif %}
{%- endwith %}

app/templates/security/change_password.html
{% extends "base.html" %}

{% from "security/_macros.html" import render_field_with_errors, render_field %}

{% include "security/_messages.html" %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Change password</h3>
        </div>
        <div class="panel-body">
            <form action="{{ url_for_security('change_password') }}" method="POST" name="change_password_form">
                {{ change_password_form.hidden_tag() }}
                {{ render_field_with_errors(change_password_form.password) }}
                {{ render_field_with_errors(change_password_form.new_password) }}
                {{ render_field_with_errors(change_password_form.new_password_confirm) }}
                {{ render_field(change_password_form.submit) }}
            </form>
        </div>
    </div>
{% endblock %}

app/templates/security/forgot_password.html
{% extends "base.html" %}

{% from "security/_macros.html" import render_field_with_errors, render_field %}

{% include "security/_messages.html" %}

{% block content %}
    <div class="panel panel-default">
        <div class="panel-heading">
            <h3 class="panel-title">Send password reset instructions</h3>
        </div>
        <div class="panel-body">
            <form action="{{ url_for_security('forgot_password') }}" method="POST" name="forgot_password_form">
            {{ forgot_password_form.hidden_tag() }}
            {{ render_field_with_errors(forgot_password_form.email) }}
            {{ render_field(forgot_password_form.submit) }}
            </form>
            {% include "security/_menu.html" %}
        </div>
    </div>
{% endblock %}

app/templates/security/login_user.html
{% extends "base.html" %}

{% from "security/_macros.html" import render_field_with_errors, render_field %}

{% include "security/_messages.html" %}

{% block content %}
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Login</h3>
    </div>
    <div class="panel-body">
        <form action="{{ url_for_security('login') }}" method="POST" name="login_user_form">
            {{ login_user_form.hidden_tag() }}
            {{ render_field_with_errors(login_user_form.email) }}
            {{ render_field_with_errors(login_user_form.password) }}
            {{ render_field_with_errors(login_user_form.remember) }}
            {{ render_field(login_user_form.next) }}
            {{ render_field(login_user_form.submit) }}
        </form>
        {% include "security/_menu.html" %}
    </div>
</div>

{% endblock %}

app/templates/security/register_user.html
{% extends "base.html" %}

{% from "security/_macros.html" import render_field_with_errors, render_field %}

{% include "security/_messages.html" %}

{% block content %}
<div class="panel panel-default">
    <div class="panel-heading">
        <h3 class="panel-title">Register</h3>
    </div>
    <div class="panel-body">
        <form action="{{ url_for_security('register') }}" method="POST" name="register_user_form">
            {{ register_user_form.hidden_tag() }}
            {{ render_field_with_errors(register_user_form.email) }}
            {{ render_field_with_errors(register_user_form.password) }}
            {% if register_user_form.password_confirm %}
            {{ render_field_with_errors(register_user_form.password_confirm) }}
            {% endif %}
            {{ render_field(register_user_form.submit) }}
        </form>

        {% include "security/_menu.html" %}
    </div>
</div>

{% endblock %}

app/templates/security/send_confirmation.html
{% from "security/_macros.html" import render_field_with_errors, render_field %}
{% include "security/_messages.html" %}
<h1>Resend confirmation instructions</h1>
<form action="{{ url_for_security('send_confirmation') }}" method="POST" name="send_confirmation_form">
  {{ send_confirmation_form.hidden_tag() }}
  {{ render_field_with_errors(send_confirmation_form.email) }}
  {{ render_field(send_confirmation_form.submit) }}
</form>
{% include "security/_menu.html" %}

app/templates/security/send_login.html
{% from "security/_macros.html" import render_field_with_errors, render_field %}
{% include "security/_messages.html" %}
<h1>Login</h1>
<form action="{{ url_for_security('login') }}" method="POST" name="send_login_form">
  {{ send_login_form.hidden_tag() }}
  {{ render_field_with_errors(send_login_form.email) }}
  {{ render_field(send_login_form.submit) }}
</form>
{% include "security/_menu.html" %}

app/templates/security/unused/reset_password.html
{% from "security/_macros.html" import render_field_with_errors, render_field %}
{% include "security/_messages.html" %}
<h1>Reset password</h1>
<form action="{{ url_for_security('reset_password', token=reset_password_token) }}" method="POST" name="reset_password_form">
  {{ reset_password_form.hidden_tag() }}
  {{ render_field_with_errors(reset_password_form.password) }}
  {{ render_field_with_errors(reset_password_form.password_confirm) }}
  {{ render_field(reset_password_form.submit) }}
</form>
{% include "security/_menu.html" %}